### ISSUE TITLE
No such file or directory: 'comfy-deploy.log'

### ISSUE THREAD

**Issue by flamed0g** [BennyKok/comfyui-deploy#16]
This issue happens when I start ComfyUI (Windows portable version). Everything seems to work but it just can't find the specific log file.

Could be due to path issues since I am using the portable version of ComfyUI.

Error:

```
FileNotFoundError: [Errno 2] No such file or directory: 'E:\\AI\\ComfyUI_windows_portable\\ComfyUI\\comfy-deploy.log'
ERROR:aiohttp.server:Error handling request
Traceback (most recent call last):
  File "E:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\aiohttp\web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\aiohttp\web_app.py", line 543, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "E:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\aiohttp\web_middlewares.py", line 114, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "E:\AI\ComfyUI_windows_portable\ComfyUI\server.py", line 47, in cache_control
    response: web.Response = await handler(request)
                             ^^^^^^^^^^^^^^^^^^^^^^
  File "E:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-deploy\custom_routes.py", line 160, in websocket_handler
    await send_first_time_log(sid)
  File "E:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-deploy\custom_routes.py", line 466, in send_first_time_log
    with open(log_file_path, 'r') as file:
         ^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by BennyKok** [comment]
I fixed by disabling this by default, so now this can be enabled only when having 
Running with 
`export CD_ENABLE_LOG=true; python main.py`
