### ISSUE TITLE
Running locally, the code reports an error：ailed to find Server Action "null". This request might be from an older or newer deployment. Original error: Invariant: Missing 'next-action' header.

### ISSUE THREAD

**Issue by Sheldongg** [BennyKok/comfyui-deploy#32]
Error: Failed to find Server Action "null". This request might be from an older or newer deployment. Original error: Invariant: Missing 'next-action' header.
    at t3 (/data/lidong/Comfyui2/ComfyUI/custom_nodes/comfyui-deploy/web/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:39:1693)
    at /data/lidong/Comfyui2/ComfyUI/custom_nodes/comfyui-deploy/web/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:38:7079
    at AsyncLocalStorage.run (node:async_hooks:338:14)
    at t4 (/data/lidong/Comfyui2/ComfyUI/custom_nodes/comfyui-deploy/web/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:38:6387)
    at rk (/data/lidong/Comfyui2/ComfyUI/custom_nodes/comfyui-deploy/web/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:39:25940)
    at /data/lidong/Comfyui2/ComfyUI/custom_nodes/comfyui-deploy/web/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:39:28648
    at AsyncLocalStorage.run (node:async_hooks:338:14)
    at Object.wrap (/data/lidong/Comfyui2/ComfyUI/custom_nodes/comfyui-deploy/web/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:36:16172)
    at /data/lidong/Comfyui2/ComfyUI/custom_nodes/comfyui-deploy/web/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:39:28536
    at AsyncLocalStorage.run (node:async_hooks:338:14)
    at Object.wrap (/data/lidong/Comfyui2/ComfyUI/custom_nodes/comfyui-deploy/web/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:36:15420)
    at r_ (/data/lidong/Comfyui2/ComfyUI/custom_nodes/comfyui-deploy/web/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:39:28463)
    at rW.render (/data/lidong/Comfyui2/ComfyUI/custom_nodes/comfyui-deploy/web/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:39:32559)
    at doRender (/data/lidong/Comfyui2/ComfyUI/custom_nodes/comfyui-deploy/web/node_modules/next/dist/server/base-server.js:1394:44)
    at cacheEntry.responseCache.get.routeKind (/data/lidong/Comfyui2/ComfyUI/custom_nodes/comfyui-deploy/web/node_modules/next/dist/server/base-server.js:1555:34)
    at ResponseCache.get (/data/lidong/Comfyui2/ComfyUI/custom_nodes/comfyui-deploy/web/node_modules/next/dist/server/response-cache/index.js:49:26)
    at DevServer.renderToResponseWithComponentsImpl (/data/lidong/Comfyui2/ComfyUI/custom_nodes/comfyui-deploy/web/node_modules/next/dist/server/base-server.js:1463:53)
    at /data/lidong/Comfyui2/ComfyUI/custom_nodes/comfyui-deploy/web/node_modules/next/dist/server/base-server.js:992:121
    at NextTracerImpl.trace (/data/lidong/Comfyui2/ComfyUI/custom_nodes/comfyui-deploy/web/node_modules/next/dist/server/lib/trace/tracer.js:104:20)
    at DevServer.renderToResponseWithComponents (/data/lidong/Comfyui2/ComfyUI/custom_nodes/comfyui-deploy/web/node_modules/next/dist/server/base-server.js:992:41)
    at DevServer.renderErrorToResponseImpl (/data/lidong/Comfyui2/ComfyUI/custom_nodes/comfyui-deploy/web/node_modules/next/dist/server/base-server.js:2114:35)
    at async pipe.req.req (/data/lidong/Comfyui2/ComfyUI/custom_nodes/comfyui-deploy/web/node_modules/next/dist/server/base-server.js:1988:30)
    at async DevServer.pipeImpl (/data/lidong/Comfyui2/ComfyUI/custom_nodes/comfyui-deploy/web/node_modules/next/dist/server/base-server.js:911:25)
    at async /data/lidong/Comfyui2/ComfyUI/custom_nodes/comfyui-deploy/web/node_modules/next/dist/server/dev/next-dev-server.js:331:20
    at async Span.traceAsyncFn (/data/lidong/Comfyui2/ComfyUI/custom_nodes/comfyui-deploy/web/node_modules/next/dist/trace/trace.js:151:20)
    at async DevServer.handleRequest (/data/lidong/Comfyui2/ComfyUI/custom_nodes/comfyui-deploy/web/node_modules/next/dist/server/dev/next-dev-server.js:328:24)
    at async invokeRender (/data/lidong/Comfyui2/ComfyUI/custom_nodes/comfyui-deploy/web/node_modules/next/dist/server/lib/router-server.js:163:21)
    at async handleRequest (/data/lidong/Comfyui2/ComfyUI/custom_nodes/comfyui-deploy/web/node_modules/next/dist/server/lib/router-server.js:357:24)
    at async requestHandlerImpl (/data/lidong/Comfyui2/ComfyUI/custom_nodes/comfyui-deploy/web/node_modules/next/dist/server/lib/router-server.js:366:13)
    at async Server.requestListener (/data/lidong/Comfyui2/ComfyUI/custom_nodes/comfyui-deploy/web/node_modules/next/dist/server/lib/start-server.js:144:13)

**Comment by BennyKok** [comment]
Can you try clearing the cache, bun I again and restart the server?
