### ISSUE TITLE
Since new update  - error

### ISSUE THREAD

**Issue by rossman22590** [BennyKok/comfyui-deploy#54]
Traceback (most recent call last):
  File "/root/pixio_app.py", line 184, in run
    queued_workflow = queue_workflow_comfy_deploy(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/pixio_app.py", line 148, in queue_workflow_comfy_deploy
    return json.loads(urllib.request.urlopen(req).read())
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/urllib/request.py", line 525, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/urllib/request.py", line 634, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/urllib/request.py", line 563, in error
    return self._call_chain(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/urllib/request.py", line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/usr/local/lib/python3.11/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 405: Method Not Allowed

**Comment by dx777** [comment]
+1. Have the same error
